### ISSUE TITLE
Run in scheme

### ISSUE THREAD

**Issue by evtk** [ebergama/sonarr-sub-downloader#2]
Would it be possible to have the subtitle search run based on a configurable scheme? I download dutch subs, but they aren't available right after release most of the time. Usually it takes up to 1-2 weeks.

Thanks!

**Comment by ebergama** [comment]
What we could do is save a list of **failed/not found** subtitles and run the script periodically in order to try to find those missed, will that work?

**Comment by evtk** [comment]
yes! that would do the job! 

Ofcourse there are optimizations we can think of, like skipping specific series for the scheme, but right now it would be awesome if the base periodically run can be implemented.

thanks!

**Comment by ebergama** [comment]
Closing the issue, fixed in [latest release](https://github.com/ebergama/sonarr-sub-downloader/releases/latest)
